#
#   ${project.name} v${project.version} by RezzedUp
#
#   ---
#
#   This plugin *requires* DiscordSRV in order to access Discord.
#   However, it will work just fine in-game regardless of whether DiscordSRV is installed or not.
#   
#   ---
#
#   Installation (Discord Setup):
#
#   - 1) Install this plugin and DiscordSRV
#        Get DiscordSRV here: https://www.spigotmc.org/resources/discordsrv.18494/
#
#   - 2) Add a "staff-chat" channel to DiscordSRV's config
#        (in: /plugins/DiscordSRV/config.yml)
#
#     EXAMPLE:
#     EXAMPLE:    # Channel links from game to Discord
#     EXAMPLE:    # Replace the "00000000000" below with your staff channel's ID
#     EXAMPLE:    Channels: {"global": "00000000000", "staff-chat": "00000000000"}
#     EXAMPLE:    #                                        ^              ^
#     EXAMPLE:    #                         All staff chat messages will be sent to this channel.
#     EXAMPLE:
#
#     IMPORTANT NOTE:
#         The channel's name can be anything on Discord (since DiscordSRV uses its channel ID) ...
#         However, it MUST be called "staff-chat" in the config.
#         **This is very important!**
#
#   - 3) Restart the server
#
#   - 4) Give staff ranks permission to use the staff chat: 'staffchat.access'
#
#   ---
#
#   This config can be reloaded in-game with: '/managestaffchat reload'
#   (Be sure to give yourself permission to manage the staff chat with: 'staffchat.manage')
#

#
#   *If* PlaceholderAPI is installed, both in-game and discord formats will utilize them.
#   That plugin is not required for the placeholders defined below.
#
#   In-Game Placeholders:
#       %message%: the chat message
#       %name%: player's name
#       %nickname%: player's nickname if they have one (falls back to regular name)
#
#   Discord Placeholders:
#       %message%: the chat message
#       %name%: discord user's name
#       %discriminator%: discord user's discriminator (#0000)
#       %nickname%: discord user's nickname if they have one (falls back to regular name)
#
#   Hex colors are supported using the &x&R&R&G&G&B&B format.
#

in-game-message-format: "&d(&5&l&oStaff&d) %name%&7:&f %message%"
discord-message-format: "&9&ldiscord &f-> &d(&5&l&oStaff&d) %name%&7:&f %message%"

#
#   Send chat messages to staff-chat if they start with a specific prefix.
#   e.g. If the prefix is "@", then saying "@hello" will send "hello" to the staff chat.
#

enable-prefixed-chat-messages: false
prefixed-chat-identifier: "@"

#
#   Automatic staff-chat toggle messages.
#

enable-staff-chat: "&d(&5&l&oStaff&d) &2->&a &nEnabled&a automatic staff chat"
disable-staff-chat: "&d(&5&l&oStaff&d) &4->&c &nDisabled&c automatic staff chat"

#
#   If a staff member leaves the server with automatic staff chat enabled,
#   this plugin will remember and remind them upon joining back.
#   All toggles will be disabled if this plugin is unloaded (e.g. if the server restarts).
#

notify-staff-chat-enabled-on-join: true
staff-chat-enabled-notification: "&d(&5&l&oStaff&d) &2->&a Automatic staff chat is &nenabled"

#
#   Should the plugin collect basic anonymous usage metrics?
#   Metrics can be found at: https://bstats.org/plugin/bukkit/DiscordSRV-Staff-Chat/11056
#

metrics: true
