name: ${project.name}
version: ${project.version}

author: RezzedUp
description: Staff chat plugin that hooks into DiscordSRV.
website: https://modrinth.com/plugin/discordsrv-staff-chat

main: com.rezzedup.discordsrv.staffchat.StaffChatPlugin
api-version: 1.13
load: POSTWORLD
softdepend: [DiscordSRV, PlaceholderAPI]

commands:
  staffchat:
    aliases: [adminchat, schat, achat, sc, ac, a]
    description: Toggle or send a message to staff chat.
    permission: staffchat.access
    usage: |-
      /<command> - toggle automatic staff chat
      /<command> <message> - send a message to the staff chat
  managestaffchat:
    aliases: [ discordsrv-staff-chat, discordsrvstaffchat, discordstaffchat, discordadminchat, manageadminchat ]
    description: Manage and get information about DiscordSRV-Staff-Chat
    permission: staffchat.manage
    usage: /<command>
  leavestaffchat:
    aliases: [leaveadminchat]
    description: Leave the staff chat (stop receiving messages).
    permission: staffchat.access
    usage: /<command>
  joinstaffchat:
    aliases: [joinadminchat]
    description: Rejoin the staff chat (receive messages again).
    permission: staffchat.access
    usage: /<command>
  togglestaffchatsounds:
    aliases: [toggleadminchatsounds]
    description: Mute or unmute staff chat sounds for yourself.
    permission: staffchat.access
    usage: /<command>

permissions:
  staffchat.*:
    children:
      staffchat.manage: true
      staffchat.access: true
  staffchat.manage:
    description: Manage the staff chat plugin in-game (e.g. reloading)
  staffchat.access:
    descriptions: Send and receive messages via staff chat
