name: ${project.name}
version: ${project.version}
author: RezzedUp

main: com.rezzedup.discordsrv.staffchat.StaffChatPlugin
api-version: 1.13
load: POSTWORLD
softdepend: [DiscordSRV, PlaceholderAPI]

commands:
  staffchat:
    description: Toggle or send a message to staff chat.
    usage: |-
      /<command> - toggle automatic staff chat
      /<command> <message> - send a message to the staff chat
    permission: staffchat.access
    aliases: [adminchat, schat, achat, sc, ac, a]
  managestaffchat:
    description: Manage and get information about DiscordSRV-Staff-Chat
    usage: /<command>
    permission: staffchat.manage
    aliases: [discordstaffchat, discordadminchat, manageadminchat]

permissions:
  staffchat.*:
    children:
      staffchat.manage: true
      staffchat.access: true
  staffchat.manage:
    description: Manage the staff chat plugin in-game (e.g. reloading)
  staffchat.access:
    descriptions: Send and receive messages via staff chat
